## 2.2節 NumPy入門


In [1]:
# NumPyのインポート
import numpy as np

# NumPy表示形式の設定
np.set_printoptions(
    suppress=True, precision=4, floatmode='fixed'
)

### 演習問題
行列 n2の最初の列の値が3で割り切れない行を残し、割り切れた行を消す処理をします。  
その処理の結果、残された行をまとめて新しい行列を作ってください。

In [2]:
# array関数による表形式の変数の定義
n2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# n2の最初の列を抽出し、ベクトル変数a1とします。
# 2.2.4項　コード2-2-12
a1 = n2[:, 0]
print(a1)

# ブロードキャスト機能を用いて、a1の各要素が
# 3で割った余りを示す配列a2を計算します
# 2.2.5項　コード2-2-18
# 割った余りの演算については1.4.2項　コード1-4-11
a2 = a1 % 3
print(a2)

# 再度ブロードキャスト機能を用いて、a1の各要素が
# 3で割り切れるかどうかを示す配列a3を作ります
# 2.2.5項　コード2-2-18
# 比較演算については1.5.1項
a3 = a2 != 0
print(a3)

# 変数a3を用いて、　n2から必要な行だけを残す計算をし
# 結果をa4に代入します。
# 2.2.4項　コード 2-2-14
a4 = n2[a3]
print(a4)

[1 5 9]
[1 2 0]
[ True  True False]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
# 以上の処理は慣れてくると1行にまとめることも可能です
a5 = n2[n2[:, 0] % 3 != 0]
print(a5)

[[1 2 3 4]
 [5 6 7 8]]
